from .base import PortfolioStatistic
from .metrics import (
    TotalReturn,
    OneYearReturn,
    YTDReturn,
    CAGR,
    BenchmarkCAGR,
    MaxDrawdown,
    DailySharpe,
    AnnualizedSharpe,
    BenchmarkAnnualizedSharpe,
    SortinoRatio,
    DailyMean,
    AnnualizedVolatility,
    BenchmarkAnnualizedVolatility,
    LastMonthDelta,
    CalmarRatio,
    Alpha,
    Beta,
)

# Convenience list of default metrics
DEFAULT_METRICS = [
    TotalReturn(),
    CAGR(),
    BenchmarkCAGR(),
    MaxDrawdown(),
    DailySharpe(),
    AnnualizedSharpe(),
    BenchmarkAnnualizedSharpe(),
    SortinoRatio(),
    DailyMean(),
    AnnualizedVolatility(),
    BenchmarkAnnualizedVolatility(),
    LastMonthDelta(),
    OneYearReturn(),
    YTDReturn(),
    CalmarRatio(),
    Alpha(),
    Beta(),
]

__all__ = [
    "PortfolioStatistic",
    "TotalReturn",
    "CAGR",
    "BenchmarkCAGR",
    "MaxDrawdown",
    "DailySharpe",
    "AnnualizedSharpe",
    "BenchmarkAnnualizedSharpe",
    "SortinoRatio",
    "DailyMean",
    "AnnualizedVolatility",
    "BenchmarkAnnualizedVolatility",
    "LastMonthDelta",
    "OneYearReturn",
    "YTDReturn",
    "CalmarRatio",
    "Alpha",
    "Beta",
    "DEFAULT_METRICS",
]
